[package]
name = "vanisol"
version = "0.1.0"
description = "vanisol"
edition = "2018"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
solana-sdk = "=1.8.1"
regex = "0.1.41"
serde_json ="1.0.68"

[dependencies.bs58]
version = "0.4.0"